import { ArrowUpRight, CheckCircle2, MessageSquareText, Shapes } from 'lucide-react'
import { audiences } from '../../data/siteData'
import { whatsappUrl } from '../../utils/whatsapp'
import { Button } from '../common/Button'
import { Container } from '../common/Container'
import { Reveal } from '../common/Reveal'
import { SectionHeading } from '../common/SectionHeading'

export function AudienceSection(){return <><section id="publicos" className="section audiences"><Container><div className="audience-head"><SectionHeading badge="Para diferentes negócios" title="Soluções digitais adaptadas à realidade de cada empresa."/><p>Independentemente do segmento, o projeto começa entendendo os objetivos, o público e o momento atual do negócio.</p></div><div className="audience-grid">{audiences.map(([Icon,label],i)=><Reveal delay={i*.025} className="audience-card" key={label}><Icon/><span>{label}</span><ArrowUpRight/></Reveal>)}</div></Container></section><section className="section commitment"><Container><SectionHeading align="center" badge="Nosso compromisso" title="O padrão de experiência que buscamos entregar."/><div className="commit-grid"><Reveal className="commit-card"><MessageSquareText/><span>01</span><h3>Comunicação clara</h3><p>Mantemos o cliente informado sobre as etapas, decisões e próximos passos.</p></Reveal><Reveal className="commit-card" delay={.08}><Shapes/><span>02</span><h3>Organização em cada etapa</h3><p>Estruturamos o projeto para evitar confusão e manter o desenvolvimento alinhado.</p></Reveal><Reveal className="commit-card" delay={.16}><CheckCircle2/><span>03</span><h3>Soluções coerentes com o negócio</h3><p>Cada escolha visual ou estratégica deve fazer sentido para os objetivos da empresa.</p></Reveal></div><blockquote>“Tecnologia só gera valor quando resolve problemas reais.”</blockquote></Container></section><section className="mid-cta"><Container><div><span>O PRÓXIMO PASSO COMEÇA AQUI</span><h2>Seu cliente já está no digital. Sua empresa também precisa estar preparada.</h2></div><Button href={whatsappUrl()} external>Começar um projeto</Button></Container></section></>}
