import { useEffect, useState } from 'react'
import { ArrowUpRight, Check, Instagram, LayoutDashboard, Smartphone, X } from 'lucide-react'
import { projects } from '../../data/siteData'
import { whatsappUrl } from '../../utils/whatsapp'
import { Button } from '../common/Button'
import { Container } from '../common/Container'
import { Reveal } from '../common/Reveal'
import { SectionHeading } from '../common/SectionHeading'
import { GrowthChart } from '../visual/GrowthChart'

function ProjectArt({type}:{type:string}){if(type==='ads')return <div className="project-art ads-art"><div className="mini-dash-head"><LayoutDashboard/><span>Campanhas</span><b>ATIVAS</b></div><div className="mini-figures"><span><small>Alcance</small><b>28.4K</b></span><span><small>Conversões</small><b>1.248</b></span></div><GrowthChart compact/><div className="mini-bars">{[40,68,52,82,64,92].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div></div>;if(type==='social')return <div className="project-art social-art"><div className="social-phone"><div><Instagram/><b>vertex.local</b></div><span className="social-avatar"/><strong>Presença que conecta.</strong><div className="social-grid">{Array.from({length:6},(_,i)=><i key={i}>V</i>)}</div></div><div className="palette-card"><i/><i/><i/><span>Identidade<br/>consistente</span></div></div>;return <div className="project-art site-art"><div className="browser-bar"><i/><i/><i/><span>seunegocio.com.br</span></div><div className="site-preview"><div><small>SOLUÇÕES PARA EMPRESAS</small><h4>Confiança em cada detalhe.</h4><span className="fake-button">Fale conosco</span></div><div className="site-cards"><i/><i/><i/></div></div><div className="site-phone"><Smartphone/><i/><i/><i/></div></div>}

export function ProjectsSection(){const[selected,setSelected]=useState<(typeof projects)[number]|null>(null);useEffect(()=>{const esc=(e:KeyboardEvent)=>e.key==='Escape'&&setSelected(null);addEventListener('keydown',esc);document.body.style.overflow=selected?'hidden':'';return()=>{removeEventListener('keydown',esc);document.body.style.overflow=''}},[selected]);return <section id="projetos" className="section projects"><Container><SectionHeading badge="Projetos conceituais" title="Experiências que unem estratégia, design e tecnologia." text="Apresentações conceituais para demonstrar como a Vertex pode estruturar diferentes soluções digitais — sem atribuir resultados a clientes reais."/><div className="projects-grid">{projects.map((p,i)=><Reveal delay={i*.08} key={p.title}><button className="project-card" onClick={()=>setSelected(p)} aria-label={`Abrir detalhes: ${p.title}`}><div className="concept-label">Projeto conceitual</div><ProjectArt type={p.type}/><div className="project-copy"><span>{p.category}</span><h3>{p.title}</h3><p>{p.text}</p><div className="tag-list">{p.tags.map(t=><span key={t}>{t}</span>)}</div><b>Ver projeto <ArrowUpRight/></b></div></button></Reveal>)}</div></Container>{selected&&<div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="project-modal" role="dialog" aria-modal="true" aria-label={selected.title}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Fechar modal"><X/></button><div className="modal-art"><ProjectArt type={selected.type}/></div><div className="modal-copy"><span className="concept-label">Projeto conceitual</span><small>{selected.category}</small><h3>{selected.title}</h3><p>{selected.text}</p><h4>Serviços envolvidos</h4><div className="modal-tags">{selected.tags.map(t=><span key={t}><Check/>{t}</span>)}</div><Button href={whatsappUrl(`Olá! Conheci a Vertex pelo site e gostaria de um projeto semelhante a: ${selected.title}.`)} external>Quero um projeto semelhante</Button></div></div></div>}</section>}
